.TH IBBOUNCELINKS 8 "August 23, 2007" "Pragmatic Infiniband Utilities" "Infiniband Diagnostics"

.SH NAME
ibbouncelinks.pl \- run ibportstate disable/enable on all ports except the port
which is currently connected to the node you are running on.

.SH SYNOPSIS
.B ibbouncelinks.pl
   [-h -t <timeout> -i <host1,host2,...> -R -S <guid>]

.SH DESCRIPTION
.PP
ibbouncelinks.pl can be used to disable then reenable all the links of a
fabric.  This is most currently useful for when switching from SDR to DDR
across an entire cluster.

.SH OPTIONS

.PP
.TP
\fB\-S <guid>\fR
bounce only the switch specified by <guid>
.TP
\fB\-t <timeout>\fR
Set the timeout the script will use to determine if a port has gone active again.
.TP
\fB\-i\fR
Specify a comma separated list of hosts, of which the links will be ignored.
.TP
\fB\-s\fR
Specify we are going TO SDR mode.  This will casued ibbouncelinks to skip ports which are already at SDR.
.TP
\fB\-d\fR
Specify we are going TO DDR mode.  This will casued ibbouncelinks to skip ports which are already at DDR.
.TP
\fB\-q\fR
Specify we are going TO QDR mode.  This will casued ibbouncelinks to skip ports which are already at QDR.
.TP
\fB\-O <guid:port>\fR
Bounce the link of a single port specified by <guid:port>\n".

.SH AUTHOR
.TP
Ira Weiny
.RI < weiny2@llnl.gov >
