#!/bin/sh
#
#  Copyright (C) 2007 The Regents of the University of California.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Ira Weiny weiny2@llnl.gov
#  UCRL-CODE-235440
#  
#  This file is part of pragmatic-infiniband-tools (PIU), useful tools to manage
#  Infiniband Clusters.
#  For details, see http://www.llnl.gov/linux/.
#  
#  PIU is free software; you can redistribute it
#  and/or modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the License,
#  or (at your option) any later version.
#  
#  PIU is distributed in the hope that it will be
#  useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
#  Public License for more details.
#  
#  You should have received a copy of the GNU General Public License along with
#  PIU; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
#

function usage
{
	echo "$0 [-hi] <lid>"
}

if [ "$1" == "-h" ]; then
	usage
	exit 1
fi

if [ "$1" == "-i" ]; then
	print_info="y"
	shift
fi

lid=$1
NR=`saquery $lid`
rc=$?
if [ "$rc" != "0" ]; then
	echo "LID ($lid) not found in SA"
	exit $rc
fi

echo $NR | grep "NodeDescription" | sed -e 's/.*NodeDescription\.*\(.*\)/\1/'

if [ "$print_info" == "y" ]; then
	echo ""
   echo "$NR"
fi

exit 0

